version: "3.7"

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpwd
      MYSQL_DATABASE: zip_code_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysq

  web-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes:
        - "./server:/app"
        - "/app/node_modules"
    expose:
      - "5000"

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "7070:3000"
    expose:
      - "7070"
    volumes:
        - "./web-client:/app"
    logging:
        driver: none
volumes:
  db_data: